version: "3.4"

services:
  transitgraphserver:
    image: transitgraphserver
    container_name: transitgraphserver
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo.docker:27017
      ONEAUTH_API: https://api.ioak.io:8010/api
      PORT: 8065
    ports:
      - 8065:8065
    networks:
      ioak-net:
        aliases:
          - transitgraphserver.docker

networks:
  ioak-net:
    name: ioak-network
